KS-5-3 Программа простой числовой лотереи
TheHazelnutCat/KotlinSprint pull request #24
Opened 2023-11-19 12:43 UTC by TheHazelnutCat

2023-11-20 21:16 UTC, ievetrov requested changes

2023-11-20 21:16 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    val rightAnswer = "20; 12"
Лучше вынести числа в разные переменные

2023-11-20 21:16 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    if ((userAnswerFirst in rightAnswer) && (userAnswerSecond in rightAnswer))
а если ввести 2 и 2? 
ты проверяешь наличие определенного символа в строке. это не сравнение с конкретными числами

2023-11-20 21:16 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    val rightAnswer = "20; 12"
Программа должна быть гибкой с минимизацией шансов допустить ошибки. Тем более как правило значения придут из базы по отдельности или парно. Но точно не строкой

2023-11-20 21:16 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    if ((userAnswerFirst in rightAnswer) && (userAnswerSecond in rightAnswer))
но если вместо строки сделать список - будет более корректно работать. но это противоречит первому комменту

2023-11-20 21:56 UTC, TheHazelnutCat commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +    val rightAnswer = "20; 12"
Значения могут прийти с помощью массива?

2023-11-21 21:48 UTC, ievetrov approved these changes
Хорошо

2023-11-21 22:32 UTC, merged