KS-5-4 Программа верификации пользователя на космическом корабле
TheHazelnutCat/KotlinSprint pull request #25
Opened 2023-11-19 13:40 UTC by TheHazelnutCat

2023-11-20 21:18 UTC, ievetrov requested changes

2023-11-20 21:18 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task4.kt
> +        "Внимание, пассажир. Моя обязанность, как обычно, незавидная, - приветствовать вас на борту корабля \"Heart of Gold\". [вздыхает...] Что ж, введи, пожалуйста, свое имя пользователя, чтобы мы
Слишком длинная строка (больше 120 символов), как правило в крупных и средних компаниях есть системы проверяющие код, которые не пропустят такое форматирование (например [Detekt](https://detekt.dev/docs/rules/formatting/#maximumlinelength)). Давай добавим переносы

2023-11-20 21:41 UTC, TheHazelnutCat commented on src/main/kotlin/lesson5/lesson5_task4.kt
> +        "Внимание, пассажир. Моя обязанность, как обычно, незавидная, - приветствовать вас на борту корабля \"Heart of Gold\". [вздыхает...] Что ж, введи, пожалуйста, свое имя пользователя, чтобы мы
Поможет ли мне в правильном написании кода одна из таких систем (Detekt), если я подключу его к IDE?

2023-11-21 21:26 UTC, ievetrov commented on src/main/kotlin/lesson5/lesson5_task4.kt
> +        "Внимание, пассажир. Моя обязанность, как обычно, незавидная, - приветствовать вас на борту корабля \"Heart of Gold\". [вздыхает...] Что ж, введи, пожалуйста, свое имя пользователя, чтобы мы
В целом - можешь использовать автоформатирование, оно как правило работает близко к правилам Detekt.

Но с другой стороны:
1) Ставишь плагин Detekt:
<img width="600" alt="Screenshot 2023-11-22 at 00 24 51" src="https://github.com/TheHazelnutCat/KotlinSprint/assets/34489023/8807a904-de4a-4590-8e5c-47bf37e02699">

2) Делаешь в настройках так:
<img width="600" alt="Screenshot 2023-11-22 at 00 26 06" src="https://github.com/TheHazelnutCat/KotlinSprint/assets/34489023/9f979d88-86dd-4c62-95eb-170f23f9cb2b">

2023-11-21 21:38 UTC, ievetrov requested changes
Не правильно понял про переносы ))
смотри:
<img width="1354" alt="Screenshot 2023-11-22 at 00 30 15" src="https://github.com/TheHazelnutCat/KotlinSprint/assets/34489023/ac1d46d6-6478-447e-89f6-ac7ce4e8bffa">

Просто строки стараются не делать слишком широкими, чтобы не бегать по строкам глазами - это утомляет.

А за текст респект, прям интерактив ))

2023-11-21 22:53 UTC, TheHazelnutCat commented on src/main/kotlin/lesson5/lesson5_task4.kt
> +        "Внимание, пассажир. Моя обязанность, как обычно, незавидная, - приветствовать вас на борту корабля \"Heart of Gold\". [вздыхает...] Что ж, введи, пожалуйста, свое имя пользователя, чтобы мы
Спасибо)

2023-11-21 23:04 UTC, TheHazelnutCat commented
Понял, мне кажется лучше переносы через \n оставить, лучше читается вывод

2023-11-21 23:36 UTC, TheHazelnutCat commented
Правильно ли я понимаю, что лучше сделать константы этих данных, чем оставить их переменными?
Текст по типу - "Пароль неверный!" лучше вынести в константу или это не критично?
Судя по тому, что я прочитал на эту тему - константы лучше делать для оптимизации производительности, но я не совсем понимаю, когда это необходимо (Например с таким длинным текстом), а когда можно не делать ("Пароль неверный")? Или это зависит от типа программы?

2023-11-22 11:28 UTC, ievetrov approved these changes
Сейчас выглядит хорошо и аккуратно!

По константам – надо понимать как они работают. После компиляции их значение хардкодится в байт код, то есть прописывается явно. Это увеличивает быстродействие, тк обычные переменные также создаются и выделяют память.

Так вот с прицелом на андройд допустим – в приложении мы делаем динамические строки. Чтобы они подтягивались в зависимости от языка на устройстве. По этой логике для обычных строк константы можно не делать.

2023-11-22 11:47 UTC, merged