KS-2-3 Обьявил переменные и сделал вывод в формате времени
TheHazelnutCat/KotlinSprint pull request #9
Opened 2023-11-16 15:03 UTC by TheHazelnutCat

2023-11-17 04:47 UTC, ievetrov requested changes

2023-11-17 04:47 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    val timeWayHours = timeWayMinutes / NUMBER_CONST
эта переменная у тебя сейчас не используется, нужна ли она вообще?

2023-11-17 04:47 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +const val NUMBER_CONST = 60
это число должно обозначать количество минут в часе, давай ее переименуем, чтобы было это было понятно из названия)

2023-11-17 04:47 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    var timeInMinutes = timeWayMinutes + timeOutMinutes
эта переменная сбивает с толку, так как ниже ты ее перезаписываешь все равно. попробуй посчитать минуты прибытия таким способом: `(timeWayMinutes + timeOutMinutes) % 60`

2023-11-17 04:47 UTC, ievetrov commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    val timeInHours = timeOutHour + (timeInMinutes / NUMBER_CONST)
эти переменные обозначают прибытие поезда, давай назовем например `arrivalHours`

2023-11-17 08:55 UTC, TheHazelnutCat commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    var timeInMinutes = timeWayMinutes + timeOutMinutes
Вау, красиво получается, спасибо

2023-11-18 06:29 UTC, ievetrov approved these changes

2023-11-18 09:58 UTC, merged